# Generated by Django 5.1.7 on 2025-04-21 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, help_text='A short description about yourself (e.g., Tech enthusiast | Photographer | Musician)', max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_by', to='accounts.userprofile')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Following',
                'verbose_name_plural': 'Followings',
                'unique_together': {('follower', 'followed')},
            },
        ),
    ]
