# Generated by Django 5.1.7 on 2025-04-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_reset_request',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
