# Generated by Django 5.1.7 on 2025-04-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_last_reset_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_visited_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
